### PR TITLE
Fixed a bug with log records with a mapping

### PR DESCRIPTION
**Pull request by mizi**

### CODE REVIEW

**Comment by ereOn** [comment]
@mizi That seems good to me. Any reason you closed the issue ?

**Comment by mizi** [comment]
Because of the PEP8 issue :)

**Comment by ereOn** [comment]
@mizi Okay, I just seen #2.

Actually you don't need to close it : you can just push to your integration branch and the pull request is updated. Not a big deal, but it helps with tracking and avoids duplicate entries ;)

Thanks anyway !

**Comment by mizi** [comment]
Oh, didn't know that. Thanks.

**Comment by ereOn** [comment]
@mizi I can't push the new version to Pypi right now but will do so this week-end.

**Pull request closed without merging**
