### PR TITLE
Python 2.6 compatibility

### PR DESCRIPTION
**Pull request by joelnordell**

### CODE REVIEW

**Comment by ereOn** [comment]
@joelnordell Thanks for this.

Can you fix the tests before I merge that ?

> ======================================================================
> ERROR: test_colorize_message_with_context (tests.test_colorizer.ColorizerTests)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/travis/build/freelan-developers/chromalog/tests/test_colorizer.py", line 263, in test_colorize_message_with_context
>     colorizer.colorize_message(message, *args, **kwargs),
>   File "/home/travis/build/freelan-developers/chromalog/chromalog/colorizer.py", line 256, in colorize_message
>     str(message).format(*args, **kwargs),
> ValueError: zero length field name in format

**Comment by joelnordell** [comment]
Yep, I'll take a look

**Comment by joelnordell** [comment]
Looks like there's more work needed to support Python 2.6 than just changing the dictionary comprehensions.  I'll push to this branch when I've got the tests passing.

**Comment by joelnordell** [comment]
OK -- all tests are passing now!  Please review, as supporting Python 2.6 ended up requiring more changes than I initially thought it would.

Do you want commits separated by topic, as I've done, or should I squash them?

**Comment by joelnordell** [comment]
@ereOn OK -- all tests are passing now. Please review, as supporting Python 2.6 ended up requiring more changes than I initially thought it would.

Do you want commits separated by topic, as I've done, or should I squash them?

**Comment by joelnordell** [comment]
Oh looks like I still need to update the `setup.py` -- will do momentarily.

**Comment by ereOn** [comment]
@joelnordell Very nice PR. Perfect.

Thanks for this. I'll merge it and release a new version immediately.

**Comment by ereOn** [comment]
@joelnordell Version 1.0.5 pushed to PyPi with new support for Python 2.6 and Python 3.5 (and a couple of fixes for Windows).

Thanks again !

**Comment by joelnordell** [comment]
@ereOn Great, thanks!

**Pull request merged**
